Repository puruagarwal1/hacktoberfest-2022-directory, pull requests merged in 2022-09, with the labels that each got.

#3 Insertion Sort
  Insertion_Sort.py
Labels: enhancement, good first issue, hacktoberfest accepted, hacktoberfest2022, hacktoberfest-accepted

#6 Create selection sort
  selection sort
Labels: good first issue, hacktoberfest accepted, hacktoberfest2022, hacktoberfest-accepted

#5 Binary Search In Trees Using C
  Trees_Search.c
Labels: good first issue, hacktoberfest accepted, hacktoberfest2022, hacktoberfest-accepted

#4 Add files via upload
  pygameproject.py
Labels: good first issue, hacktoberfest accepted, hacktoberfest2022, hacktoberfest-accepted

#7 Tree Traversal Using Nodes
  Tree Traversal Using Nodes.c
Labels: good first issue, hacktoberfest accepted, hacktoberfest2022, hacktoberfest-accepted

#8 Create minimum-difference-between-highest-and-lowest-of-k-scores.java
  minimum-difference-between-highest-and-lowest-of-k-scores.java
Labels: good first issue, hacktoberfest accepted, hacktoberfest2022, hacktoberfest-accepted

#9 Create Calculate Compound Interest.c
  Calculate Compound Interest.c
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#12 Total amount payable
  Calculate Compound Interest.c
Labels: good first issue, hacktoberfest accepted

#11 Added LongArithSubarray.cpp
  LongArithSubarray.cpp
Labels: good first issue, hacktoberfest accepted
