Repository puruagarwal1/hacktoberfest-2022-directory, pull requests merged in 2022-10, with the labels that each got.

#13 added program for binary tree inorder traversal
  binary-tree-inorder-traversal.cpp
Labels: good first issue, hacktoberfest accepted, hacktoberfest2022, hacktoberfest-accepted

#17 Divisibility Check
  Divisibility Check
Labels: good first issue, hacktoberfest accepted, hacktoberfest2022, hacktoberfest-accepted

#16 BMI Calculator
  BMI Calculator
Labels: enhancement, hacktoberfest accepted

#18 Bubble Sort C++
  bubblesort.cpp
Labels: good first issue, hacktoberfest accepted, hacktoberfest2022, hacktoberfest-accepted

#14 Create convertStringToHexadecimalString.c
  convertStringToHexadecimalString.c
Labels: good first issue, hacktoberfest accepted, hacktoberfest2022

#21 Create bucket_sort.cpp
  bucket_sort.cpp
Labels: good first issue, hacktoberfest accepted, hacktoberfest2022

#22 Improved Divisibility check code
  Divisibility Check
  divisibility_check.c
Labels: hacktoberfest accepted

#10 Update Implementing a Stack.c
  Implementing a Stack.c
Labels: hacktoberfest accepted

#24 Added new algorithm "Kadane's Algorithm"
  KadaneAlgo.java
Labels: good first issue, hacktoberfest accepted

#25 hacktoberfest-2022
  prime_number.c
Labels: good first issue, hacktoberfest accepted

#26 Modified Implementing a Stack.c
  Implementing a Stack.c
Labels: good first issue, hacktoberfest accepted

#27 Competitive programming template
  template.cpp
Labels: good first issue, hacktoberfest accepted

#58 Breadth First Search using recursion in C.
  bfs_recursion.c
Labels: good first issue, hacktoberfest accepted

#56 Create adding_numbres.c
  adding_numbres.c
Labels: good first issue, hacktoberfest accepted

#54 algorithm for searching in rotated sorted array in cpp.
  search_in_rotated_array.cpp
Labels: good first issue, hacktoberfest accepted

#60 Depth First Search using Recursion in C.
  dfs_recursion.c
Labels: good first issue, hacktoberfest accepted

#59 good leetcode questions
  majority_element.java
  median_of_two_sorted_arrays.java
  merge_sorted_array.java
  missing_number.java
  power_of_four.java
Labels: good first issue, hacktoberfest accepted

#53 Improve prime_number.c
  prime_number.c
Labels: enhancement, good first issue, hacktoberfest accepted

#52 Create RemoveDuplicates
  RemoveDuplicates
Labels: good first issue, hacktoberfest accepted

#51 Create KadaneAlgoCpp
  KadaneAlgoCpp
  WavePrint2dArray
Labels: good first issue, hacktoberfest accepted

#50 README.md updated.
  README.md
Labels: good first issue, hacktoberfest accepted

#49 #19 Implementt kadane's algorithm in C++
  Kadane-algorithm.cpp
  tempCodeRunnerFile.cpp
Labels: good first issue, hacktoberfest accepted

#75 Initial Commit
  RatInAMaze.cpp
Labels: good first issue, hacktoberfest accepted

#29 Hacktoberfest-2022
  Arraystack
  bollywood data analysis/Untitled.ipynb
  bollywood data analysis/bollywood.csv
Labels: good first issue, hacktoberfest accepted

#31 added binary search in python
  binarySearch.py
Labels: good first issue, hacktoberfest accepted

#37 Age Calculator
  AGE CALCULATOR
Labels: good first issue, hacktoberfest accepted

#44 Create DiscSchedulingFCFS.cpp
  DiscSchedulingFCFS.cpp
Labels: hacktoberfest accepted, hacktoberfest2022

#46 Add files via upload
  BinarySearch.cpp
  DFS_Recursion.c
Labels: hacktoberfest accepted, hacktoberfest2022

#48 added ML Linear Regression Algorithm
  ML-Algorithms/LinearRegression/Bengaluru_House_Data.csv
  ML-Algorithms/LinearRegression/RegressionModel.ipynb
Labels: hacktoberfest accepted, hacktoberfest2022

#66 Added QuickSort Algorithm using Java.
  QuickSort.java
Labels: enhancement, hacktoberfest accepted

#62 Created towerOfHanoi.c
  towerOfHanoi.c
  towerOfHanoi.java
  towerOfHanoi.js
  towerOfHanoi.py
Labels: good first issue, hacktoberfest accepted

#65 Create Tim Sort algorithm
  TIM SORT ALGORTHM
Labels: good first issue, hacktoberfest accepted

#67 Added Dijkstra’s shortest path algorithm
  Dijkstra’s shortest path algorithm.cpp
Labels: hacktoberfest accepted

#68 added bubblesort in python
  New Text Document.txt
  bubblesort.py
Labels: hacktoberfest accepted

#70 Create tower_of_hanoi.py
  tower_of_hanoi.py
Labels: good first issue, hacktoberfest accepted

#74 Java Program to Check Tech Number
  tech_number.java
Labels: good first issue, hacktoberfest accepted

#72 Closes #61
  mergeSort.cpp
  quickSort.cpp
  reverse_linkedlist.cpp
  reverse_linkedlist.java
  reverse_linkedlist.py
Labels: good first issue, hacktoberfest accepted

#71 comprehensive guide for STL in C++
  stl_explained.cpp
Labels: good first issue, hacktoberfest accepted

#76 Created average-binary-tree-levels.cpp
  average-binary-tree-levels.cpp
Labels: good first issue, hacktoberfest accepted

#77 Create sorting
  sorting
Labels: hacktoberfest accepted

#78 Reversing a Linked List #61 issue solution program added
  Reverse_Linked_List.cpp
Labels: hacktoberfest accepted

#81 Create Generating Strong Password using
  Generating Strong Password using
Labels: hacktoberfest accepted

#84 Added Decision Tree ML Classifier
  ML-Algorithms/DecisionTreeClassifier/Decision_Tree_Classifier.ipynb
Labels: hacktoberfest accepted

#109 quiz project
  Quiz.c
Labels: good first issue, hacktoberfest accepted

#111 sum of 3 numbers
  3sum.cpp
Labels: hacktoberfest accepted

#113 C++ programs added
  Area.cpp
  Matrix.cpp
Labels: good first issue, hacktoberfest accepted

#115 Added Bubble Sort in Golang
  bubblesort.go
Labels: good first issue, hacktoberfest accepted

#117 Create CheckPowerOf2.py
  CheckPowerOf2.py
Labels: good first issue, hacktoberfest accepted

#118 Solved the problem to check for Bipartite graph.
  check if graph is Bipartite or not.cpp
Labels: good first issue, hacktoberfest accepted

#120 SVM
  ML-Algorithms/SupportVectorMachine
Labels: good first issue, hacktoberfest accepted

#125 Create Sparse_Table.cpp
  Sparse_Table.cpp
Labels: good first issue, hacktoberfest accepted

#134 Add files via upload
  OderAgonosticBinarySearch.java
Labels: good first issue, hacktoberfest accepted

#133 Create main.py
  Aerial-distance-calculator/main.py
Labels: good first issue, hacktoberfest accepted

#136 Breadth First Search Algorithm.cpp
  Breadth First Search Algorithm.cpp
Labels: good first issue

#137 Create Depth First Search.cpp
  Depth First Search.cpp
Labels: good first issue
